FROM node:14.15.1-alpine3.12

# Set env vars
ENV PORT=80

# Create workspace
RUN mkdir /app
WORKDIR /app

# Install useful dependencies
RUN apk add git

# Copy package files and install
COPY package.json package-lock.json ./
RUN npm ci

# Add remaining files
ADD . ./

# Expose port for external access
EXPOSE $PORT

# Start dev server
CMD [ "npm", "run", "start" ]
